name: CICD
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Start Tracee profiling in background
      uses: aquasecurity/tracee-action@917a100a58607c453bbdbb14d0f8796bbec076e2

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -race -vet=off ./...

    - name: Build
      run: go build -o app -v ./...

    - name: Fake upload
      uses: josedonizetti/upload-fake-action@v0.1.0

    - name: Stop and Check Tracee results and create a PR
      uses: aquasecurity/tracee-action@e114d60efbb7d7a11f2318740304c8cfe2bfc27a
      with:
        create-pr: "true"
        fail-on-diff: "true"
