name: 02.01 Compromised CICD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  pull-requests: write

jobs:
  build:
    name: Cicd compromised
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Start Tracee profiling in background
        uses: aquasecurity/tracee-action@c04dacc040ec9a32ef10150c0ca442d311ec28fd
          #  - name: Use Node.js
   #     uses: actions/setup-node@v3
  #      with:
 #         node-version: 18.x
  #    - name: Build
   #     run: npm run build
    #    working-directory: ./my-app
      - name: Render Pages
        run: |
          echo "hello"
          echo '<div><img src="https://media.tenor.com/rePDfDWO3XoAAAAd/hacking.gif" width="518" height="388.5" alt="Hacking GIF - Hacking GIFs" style="max-width: 518px;"></div><p><h2>You Have Been Pwned!</h2>' > my-app/README.md
          cat my-app/README.md
      - name: Stop and Check Tracee results and create a PR
        uses: aquasecurity/tracee-action@ce4a8e48ea62953976e7e10fcd83344bb85d132a
        with:
          create-pr: "true"
          fail-on-diff: "false"
